//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodCrate_V1._01.DatabaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct User : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct Product : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int weightField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                if ((object.ReferenceEquals(this.pictureField, value) != true)) {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct Recipe : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long creatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FoodCrate_V1._01.DatabaseService.Ingredient[] ingredientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long recipeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string shortDescField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long creator {
            get {
                return this.creatorField;
            }
            set {
                if ((this.creatorField.Equals(value) != true)) {
                    this.creatorField = value;
                    this.RaisePropertyChanged("creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullDesc {
            get {
                return this.fullDescField;
            }
            set {
                if ((object.ReferenceEquals(this.fullDescField, value) != true)) {
                    this.fullDescField = value;
                    this.RaisePropertyChanged("fullDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FoodCrate_V1._01.DatabaseService.Ingredient[] ingredients {
            get {
                return this.ingredientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ingredientsField, value) != true)) {
                    this.ingredientsField = value;
                    this.RaisePropertyChanged("ingredients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string picture {
            get {
                return this.pictureField;
            }
            set {
                if ((object.ReferenceEquals(this.pictureField, value) != true)) {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long recipeID {
            get {
                return this.recipeIDField;
            }
            set {
                if ((this.recipeIDField.Equals(value) != true)) {
                    this.recipeIDField = value;
                    this.RaisePropertyChanged("recipeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string shortDesc {
            get {
                return this.shortDescField;
            }
            set {
                if ((object.ReferenceEquals(this.shortDescField, value) != true)) {
                    this.shortDescField = value;
                    this.RaisePropertyChanged("shortDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ingredient", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct Ingredient : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long recipeIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long recipeID {
            get {
                return this.recipeIDField;
            }
            set {
                if ((this.recipeIDField.Equals(value) != true)) {
                    this.recipeIDField = value;
                    this.RaisePropertyChanged("recipeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invoice", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct Invoice : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime creationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fullyPaidDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long invoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FoodCrate_V1._01.DatabaseService.InvoiceItem[] invoiceItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime creationDate {
            get {
                return this.creationDateField;
            }
            set {
                if ((this.creationDateField.Equals(value) != true)) {
                    this.creationDateField = value;
                    this.RaisePropertyChanged("creationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dueDate {
            get {
                return this.dueDateField;
            }
            set {
                if ((this.dueDateField.Equals(value) != true)) {
                    this.dueDateField = value;
                    this.RaisePropertyChanged("dueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fullyPaidDate {
            get {
                return this.fullyPaidDateField;
            }
            set {
                if ((this.fullyPaidDateField.Equals(value) != true)) {
                    this.fullyPaidDateField = value;
                    this.RaisePropertyChanged("fullyPaidDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long invoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                if ((this.invoiceIDField.Equals(value) != true)) {
                    this.invoiceIDField = value;
                    this.RaisePropertyChanged("invoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FoodCrate_V1._01.DatabaseService.InvoiceItem[] invoiceItems {
            get {
                return this.invoiceItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceItemsField, value) != true)) {
                    this.invoiceItemsField = value;
                    this.RaisePropertyChanged("invoiceItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceItem", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct InvoiceItem : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int discountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long invoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long invoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                if ((this.invoiceIDField.Equals(value) != true)) {
                    this.invoiceIDField = value;
                    this.RaisePropertyChanged("invoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/DatabaseService")]
    [System.SerializableAttribute()]
    public partial struct Cart : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long cartIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long productIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long cartID {
            get {
                return this.cartIDField;
            }
            set {
                if ((this.cartIDField.Equals(value) != true)) {
                    this.cartIDField = value;
                    this.RaisePropertyChanged("cartID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long productID {
            get {
                return this.productIDField;
            }
            set {
                if ((this.productIDField.Equals(value) != true)) {
                    this.productIDField = value;
                    this.RaisePropertyChanged("productID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseService.DBService")]
    public interface DBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetData", ReplyAction="http://tempuri.org/DBService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetData", ReplyAction="http://tempuri.org/DBService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/DBService/GetDataUsingDataContractResponse")]
        FoodCrate_V1._01.DatabaseService.CompositeType GetDataUsingDataContract(FoodCrate_V1._01.DatabaseService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/DBService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.CompositeType> GetDataUsingDataContractAsync(FoodCrate_V1._01.DatabaseService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TestConnection", ReplyAction="http://tempuri.org/DBService/TestConnectionResponse")]
        string TestConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TestConnection", ReplyAction="http://tempuri.org/DBService/TestConnectionResponse")]
        System.Threading.Tasks.Task<string> TestConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/ExecuteQuery", ReplyAction="http://tempuri.org/DBService/ExecuteQueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.CompositeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Recipe))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Ingredient[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Ingredient))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Invoice))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.InvoiceItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.InvoiceItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Cart[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Cart))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FoodCrate_V1._01.DatabaseService.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] ExecuteQuery(string sqlQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/ExecuteQuery", ReplyAction="http://tempuri.org/DBService/ExecuteQueryResponse")]
        System.Threading.Tasks.Task<object[]> ExecuteQueryAsync(string sqlQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/ExecuteNonQuery", ReplyAction="http://tempuri.org/DBService/ExecuteNonQueryResponse")]
        bool ExecuteNonQuery(string sqlQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/ExecuteNonQuery", ReplyAction="http://tempuri.org/DBService/ExecuteNonQueryResponse")]
        System.Threading.Tasks.Task<bool> ExecuteNonQueryAsync(string sqlQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TotalSales", ReplyAction="http://tempuri.org/DBService/TotalSalesResponse")]
        long TotalSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TotalSales", ReplyAction="http://tempuri.org/DBService/TotalSalesResponse")]
        System.Threading.Tasks.Task<long> TotalSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TotalRegisteredUsers", ReplyAction="http://tempuri.org/DBService/TotalRegisteredUsersResponse")]
        long TotalRegisteredUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TotalRegisteredUsers", ReplyAction="http://tempuri.org/DBService/TotalRegisteredUsersResponse")]
        System.Threading.Tasks.Task<long> TotalRegisteredUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/CashGenerated", ReplyAction="http://tempuri.org/DBService/CashGeneratedResponse")]
        double CashGenerated(System.DateTime fromHere, System.DateTime toHere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/CashGenerated", ReplyAction="http://tempuri.org/DBService/CashGeneratedResponse")]
        System.Threading.Tasks.Task<double> CashGeneratedAsync(System.DateTime fromHere, System.DateTime toHere);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TotalProductsSold", ReplyAction="http://tempuri.org/DBService/TotalProductsSoldResponse")]
        long TotalProductsSold();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/TotalProductsSold", ReplyAction="http://tempuri.org/DBService/TotalProductsSoldResponse")]
        System.Threading.Tasks.Task<long> TotalProductsSoldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AuthUser", ReplyAction="http://tempuri.org/DBService/AuthUserResponse")]
        int AuthUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AuthUser", ReplyAction="http://tempuri.org/DBService/AuthUserResponse")]
        System.Threading.Tasks.Task<int> AuthUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/UniqueUsername", ReplyAction="http://tempuri.org/DBService/UniqueUsernameResponse")]
        bool UniqueUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/UniqueUsername", ReplyAction="http://tempuri.org/DBService/UniqueUsernameResponse")]
        System.Threading.Tasks.Task<bool> UniqueUsernameAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/CountProducts", ReplyAction="http://tempuri.org/DBService/CountProductsResponse")]
        long CountProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/CountProducts", ReplyAction="http://tempuri.org/DBService/CountProductsResponse")]
        System.Threading.Tasks.Task<long> CountProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddUser", ReplyAction="http://tempuri.org/DBService/AddUserResponse")]
        long AddUser(string username, string name, string surname, string email, int type, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddUser", ReplyAction="http://tempuri.org/DBService/AddUserResponse")]
        System.Threading.Tasks.Task<long> AddUserAsync(string username, string name, string surname, string email, int type, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddProduct", ReplyAction="http://tempuri.org/DBService/AddProductResponse")]
        long AddProduct(string name, string type, int weight, string description, string picture, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddProduct", ReplyAction="http://tempuri.org/DBService/AddProductResponse")]
        System.Threading.Tasks.Task<long> AddProductAsync(string name, string type, int weight, string description, string picture, double price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddRecipe", ReplyAction="http://tempuri.org/DBService/AddRecipeResponse")]
        long AddRecipe(string name, long creator, string shortdesc, string fulldesc, string picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddRecipe", ReplyAction="http://tempuri.org/DBService/AddRecipeResponse")]
        System.Threading.Tasks.Task<long> AddRecipeAsync(string name, long creator, string shortdesc, string fulldesc, string picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddIngredient", ReplyAction="http://tempuri.org/DBService/AddIngredientResponse")]
        long AddIngredient(long recipeID, long productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddIngredient", ReplyAction="http://tempuri.org/DBService/AddIngredientResponse")]
        System.Threading.Tasks.Task<long> AddIngredientAsync(long recipeID, long productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddInvoice", ReplyAction="http://tempuri.org/DBService/AddInvoiceResponse")]
        long AddInvoice(long UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddInvoice", ReplyAction="http://tempuri.org/DBService/AddInvoiceResponse")]
        System.Threading.Tasks.Task<long> AddInvoiceAsync(long UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddInvoiceItem", ReplyAction="http://tempuri.org/DBService/AddInvoiceItemResponse")]
        long AddInvoiceItem(long invoiceID, long productID, int quantity, int discount, double total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddInvoiceItem", ReplyAction="http://tempuri.org/DBService/AddInvoiceItemResponse")]
        System.Threading.Tasks.Task<long> AddInvoiceItemAsync(long invoiceID, long productID, int quantity, int discount, double total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/SetUserName", ReplyAction="http://tempuri.org/DBService/SetUserNameResponse")]
        bool SetUserName(long userID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/SetUserName", ReplyAction="http://tempuri.org/DBService/SetUserNameResponse")]
        System.Threading.Tasks.Task<bool> SetUserNameAsync(long userID, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/SetUserSurname", ReplyAction="http://tempuri.org/DBService/SetUserSurnameResponse")]
        bool SetUserSurname(long userID, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/SetUserSurname", ReplyAction="http://tempuri.org/DBService/SetUserSurnameResponse")]
        System.Threading.Tasks.Task<bool> SetUserSurnameAsync(long userID, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/SetUserUsername", ReplyAction="http://tempuri.org/DBService/SetUserUsernameResponse")]
        bool SetUserUsername(long userID, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/SetUserUsername", ReplyAction="http://tempuri.org/DBService/SetUserUsernameResponse")]
        System.Threading.Tasks.Task<bool> SetUserUsernameAsync(long userID, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetUser", ReplyAction="http://tempuri.org/DBService/GetUserResponse")]
        FoodCrate_V1._01.DatabaseService.User GetUser(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetUser", ReplyAction="http://tempuri.org/DBService/GetUserResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.User> GetUserAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetUserByEmail", ReplyAction="http://tempuri.org/DBService/GetUserByEmailResponse")]
        FoodCrate_V1._01.DatabaseService.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetUserByEmail", ReplyAction="http://tempuri.org/DBService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.User> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetProduct", ReplyAction="http://tempuri.org/DBService/GetProductResponse")]
        FoodCrate_V1._01.DatabaseService.Product GetProduct(long productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetProduct", ReplyAction="http://tempuri.org/DBService/GetProductResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Product> GetProductAsync(long productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetRecipe", ReplyAction="http://tempuri.org/DBService/GetRecipeResponse")]
        FoodCrate_V1._01.DatabaseService.Recipe GetRecipe(long recipeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetRecipe", ReplyAction="http://tempuri.org/DBService/GetRecipeResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Recipe> GetRecipeAsync(long recipeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetIngredient", ReplyAction="http://tempuri.org/DBService/GetIngredientResponse")]
        FoodCrate_V1._01.DatabaseService.Ingredient GetIngredient(long ingredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetIngredient", ReplyAction="http://tempuri.org/DBService/GetIngredientResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Ingredient> GetIngredientAsync(long ingredientID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetInvoice", ReplyAction="http://tempuri.org/DBService/GetInvoiceResponse")]
        FoodCrate_V1._01.DatabaseService.Invoice GetInvoice(long invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetInvoice", ReplyAction="http://tempuri.org/DBService/GetInvoiceResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Invoice> GetInvoiceAsync(long invoiceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetInvoiceItem", ReplyAction="http://tempuri.org/DBService/GetInvoiceItemResponse")]
        FoodCrate_V1._01.DatabaseService.InvoiceItem GetInvoiceItem(long invoiceItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetInvoiceItem", ReplyAction="http://tempuri.org/DBService/GetInvoiceItemResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.InvoiceItem> GetInvoiceItemAsync(long invoiceItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddCart", ReplyAction="http://tempuri.org/DBService/AddCartResponse")]
        long AddCart(long userID, long productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/AddCart", ReplyAction="http://tempuri.org/DBService/AddCartResponse")]
        System.Threading.Tasks.Task<long> AddCartAsync(long userID, long productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/CheckForCart", ReplyAction="http://tempuri.org/DBService/CheckForCartResponse")]
        bool CheckForCart(long userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/CheckForCart", ReplyAction="http://tempuri.org/DBService/CheckForCartResponse")]
        System.Threading.Tasks.Task<bool> CheckForCartAsync(long userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/RemoveCartItem", ReplyAction="http://tempuri.org/DBService/RemoveCartItemResponse")]
        bool RemoveCartItem(long cartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/RemoveCartItem", ReplyAction="http://tempuri.org/DBService/RemoveCartItemResponse")]
        System.Threading.Tasks.Task<bool> RemoveCartItemAsync(long cartID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetCart", ReplyAction="http://tempuri.org/DBService/GetCartResponse")]
        FoodCrate_V1._01.DatabaseService.Cart[] GetCart(long userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetCart", ReplyAction="http://tempuri.org/DBService/GetCartResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Cart[]> GetCartAsync(long userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/RemoveProduct", ReplyAction="http://tempuri.org/DBService/RemoveProductResponse")]
        bool RemoveProduct(long productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/RemoveProduct", ReplyAction="http://tempuri.org/DBService/RemoveProductResponse")]
        System.Threading.Tasks.Task<bool> RemoveProductAsync(long productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetProductByString", ReplyAction="http://tempuri.org/DBService/GetProductByStringResponse")]
        FoodCrate_V1._01.DatabaseService.Product[] GetProductByString(string NameOrType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DBService/GetProductByString", ReplyAction="http://tempuri.org/DBService/GetProductByStringResponse")]
        System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Product[]> GetProductByStringAsync(string NameOrType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBServiceChannel : FoodCrate_V1._01.DatabaseService.DBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<FoodCrate_V1._01.DatabaseService.DBService>, FoodCrate_V1._01.DatabaseService.DBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public FoodCrate_V1._01.DatabaseService.CompositeType GetDataUsingDataContract(FoodCrate_V1._01.DatabaseService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.CompositeType> GetDataUsingDataContractAsync(FoodCrate_V1._01.DatabaseService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string TestConnection() {
            return base.Channel.TestConnection();
        }
        
        public System.Threading.Tasks.Task<string> TestConnectionAsync() {
            return base.Channel.TestConnectionAsync();
        }
        
        public object[] ExecuteQuery(string sqlQuery) {
            return base.Channel.ExecuteQuery(sqlQuery);
        }
        
        public System.Threading.Tasks.Task<object[]> ExecuteQueryAsync(string sqlQuery) {
            return base.Channel.ExecuteQueryAsync(sqlQuery);
        }
        
        public bool ExecuteNonQuery(string sqlQuery) {
            return base.Channel.ExecuteNonQuery(sqlQuery);
        }
        
        public System.Threading.Tasks.Task<bool> ExecuteNonQueryAsync(string sqlQuery) {
            return base.Channel.ExecuteNonQueryAsync(sqlQuery);
        }
        
        public long TotalSales() {
            return base.Channel.TotalSales();
        }
        
        public System.Threading.Tasks.Task<long> TotalSalesAsync() {
            return base.Channel.TotalSalesAsync();
        }
        
        public long TotalRegisteredUsers() {
            return base.Channel.TotalRegisteredUsers();
        }
        
        public System.Threading.Tasks.Task<long> TotalRegisteredUsersAsync() {
            return base.Channel.TotalRegisteredUsersAsync();
        }
        
        public double CashGenerated(System.DateTime fromHere, System.DateTime toHere) {
            return base.Channel.CashGenerated(fromHere, toHere);
        }
        
        public System.Threading.Tasks.Task<double> CashGeneratedAsync(System.DateTime fromHere, System.DateTime toHere) {
            return base.Channel.CashGeneratedAsync(fromHere, toHere);
        }
        
        public long TotalProductsSold() {
            return base.Channel.TotalProductsSold();
        }
        
        public System.Threading.Tasks.Task<long> TotalProductsSoldAsync() {
            return base.Channel.TotalProductsSoldAsync();
        }
        
        public int AuthUser(string email, string password) {
            return base.Channel.AuthUser(email, password);
        }
        
        public System.Threading.Tasks.Task<int> AuthUserAsync(string email, string password) {
            return base.Channel.AuthUserAsync(email, password);
        }
        
        public bool UniqueUsername(string username) {
            return base.Channel.UniqueUsername(username);
        }
        
        public System.Threading.Tasks.Task<bool> UniqueUsernameAsync(string username) {
            return base.Channel.UniqueUsernameAsync(username);
        }
        
        public long CountProducts() {
            return base.Channel.CountProducts();
        }
        
        public System.Threading.Tasks.Task<long> CountProductsAsync() {
            return base.Channel.CountProductsAsync();
        }
        
        public long AddUser(string username, string name, string surname, string email, int type, string password) {
            return base.Channel.AddUser(username, name, surname, email, type, password);
        }
        
        public System.Threading.Tasks.Task<long> AddUserAsync(string username, string name, string surname, string email, int type, string password) {
            return base.Channel.AddUserAsync(username, name, surname, email, type, password);
        }
        
        public long AddProduct(string name, string type, int weight, string description, string picture, double price) {
            return base.Channel.AddProduct(name, type, weight, description, picture, price);
        }
        
        public System.Threading.Tasks.Task<long> AddProductAsync(string name, string type, int weight, string description, string picture, double price) {
            return base.Channel.AddProductAsync(name, type, weight, description, picture, price);
        }
        
        public long AddRecipe(string name, long creator, string shortdesc, string fulldesc, string picture) {
            return base.Channel.AddRecipe(name, creator, shortdesc, fulldesc, picture);
        }
        
        public System.Threading.Tasks.Task<long> AddRecipeAsync(string name, long creator, string shortdesc, string fulldesc, string picture) {
            return base.Channel.AddRecipeAsync(name, creator, shortdesc, fulldesc, picture);
        }
        
        public long AddIngredient(long recipeID, long productID, int quantity) {
            return base.Channel.AddIngredient(recipeID, productID, quantity);
        }
        
        public System.Threading.Tasks.Task<long> AddIngredientAsync(long recipeID, long productID, int quantity) {
            return base.Channel.AddIngredientAsync(recipeID, productID, quantity);
        }
        
        public long AddInvoice(long UserID) {
            return base.Channel.AddInvoice(UserID);
        }
        
        public System.Threading.Tasks.Task<long> AddInvoiceAsync(long UserID) {
            return base.Channel.AddInvoiceAsync(UserID);
        }
        
        public long AddInvoiceItem(long invoiceID, long productID, int quantity, int discount, double total) {
            return base.Channel.AddInvoiceItem(invoiceID, productID, quantity, discount, total);
        }
        
        public System.Threading.Tasks.Task<long> AddInvoiceItemAsync(long invoiceID, long productID, int quantity, int discount, double total) {
            return base.Channel.AddInvoiceItemAsync(invoiceID, productID, quantity, discount, total);
        }
        
        public bool SetUserName(long userID, string name) {
            return base.Channel.SetUserName(userID, name);
        }
        
        public System.Threading.Tasks.Task<bool> SetUserNameAsync(long userID, string name) {
            return base.Channel.SetUserNameAsync(userID, name);
        }
        
        public bool SetUserSurname(long userID, string surname) {
            return base.Channel.SetUserSurname(userID, surname);
        }
        
        public System.Threading.Tasks.Task<bool> SetUserSurnameAsync(long userID, string surname) {
            return base.Channel.SetUserSurnameAsync(userID, surname);
        }
        
        public bool SetUserUsername(long userID, string username) {
            return base.Channel.SetUserUsername(userID, username);
        }
        
        public System.Threading.Tasks.Task<bool> SetUserUsernameAsync(long userID, string username) {
            return base.Channel.SetUserUsernameAsync(userID, username);
        }
        
        public FoodCrate_V1._01.DatabaseService.User GetUser(string email, string password) {
            return base.Channel.GetUser(email, password);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.User> GetUserAsync(string email, string password) {
            return base.Channel.GetUserAsync(email, password);
        }
        
        public FoodCrate_V1._01.DatabaseService.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.User> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public FoodCrate_V1._01.DatabaseService.Product GetProduct(long productID) {
            return base.Channel.GetProduct(productID);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Product> GetProductAsync(long productID) {
            return base.Channel.GetProductAsync(productID);
        }
        
        public FoodCrate_V1._01.DatabaseService.Recipe GetRecipe(long recipeID) {
            return base.Channel.GetRecipe(recipeID);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Recipe> GetRecipeAsync(long recipeID) {
            return base.Channel.GetRecipeAsync(recipeID);
        }
        
        public FoodCrate_V1._01.DatabaseService.Ingredient GetIngredient(long ingredientID) {
            return base.Channel.GetIngredient(ingredientID);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Ingredient> GetIngredientAsync(long ingredientID) {
            return base.Channel.GetIngredientAsync(ingredientID);
        }
        
        public FoodCrate_V1._01.DatabaseService.Invoice GetInvoice(long invoiceID) {
            return base.Channel.GetInvoice(invoiceID);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Invoice> GetInvoiceAsync(long invoiceID) {
            return base.Channel.GetInvoiceAsync(invoiceID);
        }
        
        public FoodCrate_V1._01.DatabaseService.InvoiceItem GetInvoiceItem(long invoiceItemID) {
            return base.Channel.GetInvoiceItem(invoiceItemID);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.InvoiceItem> GetInvoiceItemAsync(long invoiceItemID) {
            return base.Channel.GetInvoiceItemAsync(invoiceItemID);
        }
        
        public long AddCart(long userID, long productID, int quantity) {
            return base.Channel.AddCart(userID, productID, quantity);
        }
        
        public System.Threading.Tasks.Task<long> AddCartAsync(long userID, long productID, int quantity) {
            return base.Channel.AddCartAsync(userID, productID, quantity);
        }
        
        public bool CheckForCart(long userID) {
            return base.Channel.CheckForCart(userID);
        }
        
        public System.Threading.Tasks.Task<bool> CheckForCartAsync(long userID) {
            return base.Channel.CheckForCartAsync(userID);
        }
        
        public bool RemoveCartItem(long cartID) {
            return base.Channel.RemoveCartItem(cartID);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveCartItemAsync(long cartID) {
            return base.Channel.RemoveCartItemAsync(cartID);
        }
        
        public FoodCrate_V1._01.DatabaseService.Cart[] GetCart(long userID) {
            return base.Channel.GetCart(userID);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Cart[]> GetCartAsync(long userID) {
            return base.Channel.GetCartAsync(userID);
        }
        
        public bool RemoveProduct(long productID) {
            return base.Channel.RemoveProduct(productID);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveProductAsync(long productID) {
            return base.Channel.RemoveProductAsync(productID);
        }
        
        public FoodCrate_V1._01.DatabaseService.Product[] GetProductByString(string NameOrType) {
            return base.Channel.GetProductByString(NameOrType);
        }
        
        public System.Threading.Tasks.Task<FoodCrate_V1._01.DatabaseService.Product[]> GetProductByStringAsync(string NameOrType) {
            return base.Channel.GetProductByStringAsync(NameOrType);
        }
    }
}
