CREATE DATABASE FoodCrateDB;

CREATE TABLE FoodCrateDB.Products(
ProductID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
Type VARCHAR(20) NOT NULL,
Weight INT NOT NULL,
Description VARCHAR(255) NULL,
Picture VARCHAR(50) NOT NULL,
Price FLOAT NOT NULL,
PRIMARY KEY (ProductID)
);

CREATE TABLE FoodCrateDB.Invoices(
InvoiceID INT NOT NULL AUTO_INCREMENT,
UserID INT NOT NULL,
CreationDate DATE NOT NULL,
DueDate DATE NOT NULL,
FullyPaidDate DATE NULL,
Status VARCHAR(20) NOT NULL,
PRIMARY KEY (InvoiceID)
);

	
CREATE TABLE FoodCrateDB.UserTypes(
UserTypeID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(20) NOT NULL,
PRIMARY KEY (UserTypeID)
);

CREATE TABLE FoodCrateDB.Users(
UserID INT NOT NULL AUTO_INCREMENT,
UserName VARCHAR(50) NOT NULL,
Name VARCHAR(50) NOT NULL,
Surname VARCHAR(50) NOT NULL,
Email VARCHAR(100) NOT NULL,
Type INT NOT NULL,
Password VARCHAR(255) NOT NULL,
PRIMARY KEY (UserID),
UNIQUE (UserName)
);

ALTER TABLE FoodCrateDB.Users
ADD FOREIGN KEY (Type)
REFERENCES UserTypes(UserTypeID);


CREATE TABLE FoodCrateDB.Recipes(
RecipeID INT NOT NULL AUTO_INCREMENT,
Name VARCHAR(50) NOT NULL,
Creator INT NOT NULL,
ShortDesc VARCHAR(128) NOT NULL,
FullDesc VARCHAR(255) NOT NULL,
Picture VARCHAR(50) NOT NULL,
PRIMARY KEY (RecipeID)
);

ALTER TABLE FoodCrateDB.Recipes
ADD FOREIGN KEY (Creator)
REFERENCES Users(UserID);

CREATE TABLE FoodCrateDB.Ingredients(
RecipeID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL,
PRIMARY KEY (RecipeID, ProductID)
);

ALTER TABLE FoodCrateDB.Ingredients
ADD FOREIGN KEY (RecipeID)
REFERENCES Recipes(RecipeID);

ALTER TABLE FoodCrateDB.Ingredients
ADD FOREIGN KEY (ProductID)
REFERENCES Products(ProductID);

CREATE TABLE FoodCrateDB.InvoiceItems(
InvoiceID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL,
Discount INT NULL,
Total FLOAT NOT NULL,
PRIMARY KEY (InvoiceID, ProductID)
);

ALTER TABLE FoodCrateDB.InvoiceItems
ADD FOREIGN KEY (InvoiceID)
REFERENCES Invoices(InvoiceID);

ALTER TABLE FoodCrateDB.InvoiceItems
ADD FOREIGN KEY (ProductID)
REFERENCES Products(ProductID);

DROP DATABASE foodcratedb;